function ydotRCB=znxpfun1RCB(tRCB,yRCB)
global v kPsi G kr sigmarRCB1 sigmathiRCB1 ...
     C1RCB C2RCB rC

sigmarRCB1=C2RCB*tRCB^(-1 + kr)*(-1 + kr)/tRCB;
sigmathiRCB1=(C2RCB*tRCB^(-1 + kr)*(-1 + kr)/tRCB)*kr;

ydotRCB=[yRCB(2);...
-((-1/tRCB)*yRCB(2)*(kPsi-1))-...
(rC*((v*kPsi-kPsi-v)/(2*G))*(sigmathiRCB1))-...
(rC*((1-v+v*kPsi)/(2*G))*(sigmarRCB1))];
end